# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8383464c30a90287c27923b90a17d995e0dae5376beefd72a5fe8d57aa59de4faeaa021ef60f6f3cfaf23b35d7d7c7d3e631e25307cc477e408e3d745092e131

test:
  secret_key_base: 4531cd2ce307988b76cf52aecf21b16770b690472110282d63fbc7f95de7f896947802680e760e264fbe4229e3f945758e342a30d639a79771466c01f001ba97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
